#!/bin/bash

# Pre-commit hook for both front-end and back-end
./.husky-scripts/pre-commit/start-message.sh
./.husky-scripts/pre-commit/validate-config-files.sh
./.husky-scripts/pre-commit/run-prettier-and-linter.sh
./.husky-scripts/pre-commit/run-tests.sh
./.husky-scripts/final-success-message.sh
